import FreeImg from './free.png'
import WhiteImg from './white.png'
import browny1 from './browny1.png'
import Apro from './Apro.png'
import Epro from './Epro.png'
import ModalKpro from './ModalKpro.png'
import ani1 from './ani1.png'
import ani2 from './ani2.png'
import ani3 from './ani3.png'
import ModalAni1 from './ModalAni1.png'
import Kproblem from './Kpro1.png'
import KP1 from './KP1.png'
import KP2 from './KP2.png'
import KP3 from './KP3.png'
import EP1 from './EP1.png'
import EP2 from './EP2.png'
import EP3 from './EP3.png'
import browny8 from './browny8.png'
import browny9 from './browny9.png'


export {FreeImg , WhiteImg , browny1 , Apro , Epro , ModalKpro, ani1 , ani2 , ani3 , ModalAni1, Kproblem ,KP1, KP2, KP3, EP1, EP2, EP3 , browny8, browny9};